# Generated by Django 5.2.4 on 2025-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField()),
            ],
        ),
    ]
