# Generated by Django 5.2.4 on 2025-08-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_autor_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editora',
            old_name='nome',
            new_name='editora',
        ),
    ]
