# Generated by Django 5.2.4 on 2025-08-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_editora_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='name',
            new_name='autor',
        ),
    ]
